export const listOfCountries = [
  {
    id: 1,
    englishLabel: "Australia",
    russianLabel: "Австралия ",
    continent: "oc",
  },
  { id: 2, englishLabel: "Austria", russianLabel: "Австрия", continent: "eu" },
  {
    id: 3,
    englishLabel: "Azerbaijan",
    russianLabel: "Азербайджан",
    continent: "as",
  },
  { id: 4, englishLabel: "Albania", russianLabel: "Албания", continent: "eu" },
  { id: 5, englishLabel: "Algeria", russianLabel: "Алжир", continent: "af" },
  { id: 6, englishLabel: "Anguilla", russianLabel: "Ангилья", continent: "sa" },
  { id: 7, englishLabel: "Angola", russianLabel: "Ангола", continent: "af" },
  { id: 8, englishLabel: "Andorra", russianLabel: "Андорра", continent: "eu" },
  {
    id: 9,
    englishLabel: "Antarctica",
    russianLabel: "Антарктида",
    continent: "",
  },
  {
    id: 10,
    englishLabel: "Antigua & Barbuda",
    russianLabel: "Антигуа и Барбуда",
    continent: "na",
  },
  {
    id: 11,
    englishLabel: "Argentina",
    russianLabel: "Аргентина ",
    continent: "sa",
  },
  { id: 12, englishLabel: "Armenia", russianLabel: "Армения", continent: "as" },
  { id: 13, englishLabel: "Aruba", russianLabel: "Аруба", continent: "sa" },
  {
    id: 14,
    englishLabel: "Afghanistan",
    russianLabel: "Афганистан",
    continent: "as",
  },
  {
    id: 15,
    englishLabel: "American Samoa",
    russianLabel: "Американское Самоа",
    continent: "oc",
  },
  {
    id: 16,
    englishLabel: "Bahamas",
    russianLabel: "Багамские о-ва",
    continent: "na",
  },
  {
    id: 17,
    englishLabel: "Bangladesh",
    russianLabel: "Бангладеш",
    continent: "as",
  },
  {
    id: 18,
    englishLabel: "Barbados",
    russianLabel: "Барбадос",
    continent: "na",
  },
  { id: 19, englishLabel: "Bahrain", russianLabel: "Бахрейн", continent: "as" },
  {
    id: 20,
    englishLabel: "Belarus",
    russianLabel: "Беларусь",
    continent: "eu",
  },
  { id: 21, englishLabel: "Belize", russianLabel: "Белиз", continent: "na" },
  { id: 22, englishLabel: "Belgium", russianLabel: "Бельгия", continent: "eu" },
  { id: 23, englishLabel: "Benin", russianLabel: "Бенин", continent: "af" },
  {
    id: 24,
    englishLabel: "Bermuda",
    russianLabel: "Бермудские о-ва",
    continent: "na",
  },
  {
    id: 25,
    englishLabel: "Bulgaria",
    russianLabel: "Болгария",
    continent: "eu",
  },
  { id: 26, englishLabel: "Bolivia", russianLabel: "Боливия", continent: "sa" },
  {
    id: 27,
    englishLabel: "Bonaire, Sint Eustatius & Saba",
    russianLabel: "Бонайре, Синт-Эстатиус и Саба",
    continent: "na",
  },
  {
    id: 28,
    englishLabel: "Bosnia and Herzegovina",
    russianLabel: "Босния и Герцеговина",
    continent: "eu",
  },
  {
    id: 29,
    englishLabel: "Botswana",
    russianLabel: "Ботсвана",
    continent: "af",
  },
  { id: 30, englishLabel: "Brazil", russianLabel: "Бразилия", continent: "sa" },
  { id: 31, englishLabel: "Brunei", russianLabel: "Бруней", continent: "as" },
  {
    id: 32,
    englishLabel: "Burkina Faso",
    russianLabel: "Буркина-Фасо",
    continent: "af",
  },
  {
    id: 33,
    englishLabel: "Burundi ",
    russianLabel: "Бурунди ",
    continent: "af",
  },
  { id: 34, englishLabel: "Butane", russianLabel: "Бутан", continent: "as" },
  { id: 35, englishLabel: "Vanuatu", russianLabel: "Вануату", continent: "oc" },
  { id: 36, englishLabel: "Hungary", russianLabel: "Венгрия", continent: "eu" },
  {
    id: 37,
    englishLabel: "Venezuela",
    russianLabel: "Венесуэла",
    continent: "sa",
  },
  {
    id: 38,
    englishLabel: "UK",
    russianLabel: "Великобритания",
    continent: "eu",
  },
  {
    id: 39,
    englishLabel: "Virgin Is.",
    russianLabel: "Виргинские о-ва",
    continent: "na",
  },
  { id: 40, englishLabel: "Vietnam", russianLabel: "Вьетнам", continent: "as" },
  { id: 41, englishLabel: "Gabon", russianLabel: "Габон", continent: "af" },
  { id: 42, englishLabel: "Haiti", russianLabel: "Гаити", continent: "na" },
  { id: 43, englishLabel: "Guyana", russianLabel: "Гайана", continent: "sa" },
  { id: 44, englishLabel: "Gambia", russianLabel: "Гамбия", continent: "af" },
  { id: 45, englishLabel: "Ghana", russianLabel: "Гана", continent: "af" },
  {
    id: 46,
    englishLabel: "Guadeloupe",
    russianLabel: "Гваделупа",
    continent: "na",
  },
  {
    id: 47,
    englishLabel: "Guatemala",
    russianLabel: "Гватемала",
    continent: "na",
  },
  { id: 48, englishLabel: "Guinea", russianLabel: "Гвинея", continent: "af" },
  {
    id: 49,
    englishLabel: "Guinea-Bissau",
    russianLabel: "Гвинея-Бисау",
    continent: "af",
  },
  { id: 50, englishLabel: "Guernsey", russianLabel: "Гернси", continent: "eu" },
  {
    id: 51,
    englishLabel: "Germany",
    russianLabel: "Германия",
    continent: "eu",
  },
  {
    id: 52,
    englishLabel: "Gibraltar",
    russianLabel: "Гибралтар",
    continent: "eu",
  },
  {
    id: 53,
    englishLabel: "Honduras ",
    russianLabel: "Гондурас",
    continent: "na",
  },
  {
    id: 54,
    englishLabel: "Hong Kong",
    russianLabel: "Гонконг",
    continent: "as",
  },
  {
    id: 55,
    englishLabel: "Grenada ",
    russianLabel: "Гренада",
    continent: "na",
  },
  {
    id: 56,
    englishLabel: "Greenland",
    russianLabel: "Гренландия",
    continent: "eu",
  },
  { id: 57, englishLabel: "Greece", russianLabel: "Греция", continent: "eu" },
  { id: 58, englishLabel: "Georgia", russianLabel: "Грузия", continent: "as" },
  { id: 59, englishLabel: "Guam", russianLabel: "Гуам", continent: "oc" },
  { id: 60, englishLabel: "Denmark", russianLabel: "Дания", continent: "eu" },
  {
    id: 61,
    englishLabel: "Djibouti",
    russianLabel: "Джибути",
    continent: "af",
  },
  {
    id: 62,
    englishLabel: "Dominica",
    russianLabel: "Доминика",
    continent: "na",
  },
  {
    id: 63,
    englishLabel: "Dominican Republic",
    russianLabel: "Доминиканская Республика",
    continent: "na",
  },
  { id: 64, englishLabel: "Egypt", russianLabel: "Египет", continent: "af" },
  { id: 65, englishLabel: "Zambia", russianLabel: "Замбия", continent: "na" },
  {
    id: 66,
    englishLabel: "West Sahar",
    russianLabel: "Западная Сахара",
    continent: "af",
  },
  {
    id: 67,
    englishLabel: "Zimbabwe",
    russianLabel: "Зимбабве",
    continent: "sa",
  },
  { id: 68, englishLabel: "Israel", russianLabel: "Израиль", continent: "as" },
  { id: 69, englishLabel: "India", russianLabel: "Индия", continent: "as" },
  {
    id: 70,
    englishLabel: "Indonesia",
    russianLabel: "Индонезия",
    continent: "as",
  },
  { id: 71, englishLabel: "Jordan", russianLabel: "Иордания", continent: "as" },
  { id: 72, englishLabel: "Iraq", russianLabel: "Ирак", continent: "as" },
  {
    id: 73,
    englishLabel: "Ireland",
    russianLabel: "Ирландия",
    continent: "eu",
  },
  {
    id: 74,
    englishLabel: "Iceland",
    russianLabel: "Исландия",
    continent: "eu",
  },
  { id: 75, englishLabel: "Spain", russianLabel: "Испания", continent: "eu" },
  { id: 76, englishLabel: "Italy", russianLabel: "Италия", continent: "eu" },
  { id: 77, englishLabel: "Yemen", russianLabel: "Йемен", continent: "as" },
  {
    id: 78,
    englishLabel: "Cape Verde",
    russianLabel: "Кабо-Верде",
    continent: "af",
  },
  { id: 79, englishLabel: "Canada", russianLabel: "Канада", continent: "na" },
  {
    id: 80,
    englishLabel: "Kazakhstan",
    russianLabel: "Казахстан",
    continent: "as",
  },
  {
    id: 81,
    englishLabel: "Cayman Is.",
    russianLabel: "Каймановы о-ва",
    continent: "na",
  },
  {
    id: 82,
    englishLabel: "Cambodia",
    russianLabel: "Камбоджа",
    continent: "as",
  },
  {
    id: 83,
    englishLabel: "Cameroon",
    russianLabel: "Камерун",
    continent: "af",
  },
  { id: 84, englishLabel: "Qatar", russianLabel: "Катар", continent: "as" },
  { id: 85, englishLabel: "Kenya", russianLabel: "Кения", continent: "af" },
  { id: 86, englishLabel: "Cyprus", russianLabel: "Кипр", continent: "as" },
  {
    id: 87,
    englishLabel: "Kyrgyzstan",
    russianLabel: "Киргизия",
    continent: "as",
  },
  {
    id: 88,
    englishLabel: "Kiribati",
    russianLabel: "Кирибати",
    continent: "oc",
  },
  { id: 89, englishLabel: "China", russianLabel: "Китай", continent: "as" },
  {
    id: 90,
    englishLabel: "Cocos (Keeling) Is.",
    russianLabel: "Кокосовые(Килинг) о-ва",
    continent: "oc",
  },
  {
    id: 91,
    englishLabel: "Colombia",
    russianLabel: "Колумбия",
    continent: "sa",
  },
  {
    id: 92,
    englishLabel: "Comoros Is.",
    russianLabel: "Коморские о-ва",
    continent: "af",
  },
  { id: 93, englishLabel: "Congo", russianLabel: "Конго", continent: "af" },
  {
    id: 94,
    englishLabel: "Democratic Republic of the Congo",
    russianLabel: "Конго (Демократическая республика)",
    continent: "af",
  },
  { id: 95, englishLabel: "Kosovo", russianLabel: "Косово", continent: "eu" },
  {
    id: 96,
    englishLabel: "Costa Rica",
    russianLabel: "Коста-Рика",
    continent: "na",
  },
  {
    id: 97,
    englishLabel: "Ivory Coast",
    russianLabel: "Кот-д`Ивуар",
    continent: "af",
  },
  { id: 98, englishLabel: "Kuwait", russianLabel: "Кувейт", continent: "as" },
  { id: 99, englishLabel: "Curacao", russianLabel: "Кюрасао", continent: "sa" },
  { id: 100, englishLabel: "Laos", russianLabel: "Лаос", continent: "as" },
  { id: 101, englishLabel: "Latvia", russianLabel: "Латвия", continent: "eu" },
  { id: 102, englishLabel: "Lesotho", russianLabel: "Лесото", continent: "af" },
  {
    id: 103,
    englishLabel: "Liberia",
    russianLabel: "Либерия",
    continent: "af",
  },
  { id: 104, englishLabel: "Lebanon", russianLabel: "Ливан", continent: "as" },
  { id: 105, englishLabel: "Libya", russianLabel: "Ливия", continent: "af" },
  {
    id: 106,
    englishLabel: "Lithuania",
    russianLabel: "Литва",
    continent: "eu",
  },
  {
    id: 107,
    englishLabel: "Liechtenstein",
    russianLabel: "Лихтенштейн",
    continent: "eu",
  },
  {
    id: 108,
    englishLabel: "Luxembourg",
    russianLabel: "Люксембург",
    continent: "eu",
  },
  {
    id: 109,
    englishLabel: "Mauritius",
    russianLabel: "Маврикий",
    continent: "af",
  },
  {
    id: 110,
    englishLabel: "Mauritania",
    russianLabel: "Мавритания",
    continent: "af",
  },
  {
    id: 111,
    englishLabel: "Madagascar",
    russianLabel: "Мадагаскар",
    continent: "af",
  },
  {
    id: 112,
    englishLabel: "Mayotte",
    russianLabel: "Майотта",
    continent: "af",
  },
  { id: 113, englishLabel: "Macau", russianLabel: "Макао", continent: "as" },
  { id: 114, englishLabel: "Malawi", russianLabel: "Малави", continent: "af" },
  {
    id: 115,
    englishLabel: "Malaysia",
    russianLabel: "Малайзия",
    continent: "as",
  },
  { id: 116, englishLabel: "Mali", russianLabel: "Мали", continent: "af" },
  {
    id: 117,
    englishLabel: "Maldives",
    russianLabel: "Мальдивы",
    continent: "as",
  },
  { id: 118, englishLabel: "Malta", russianLabel: "Мальта", continent: "eu" },
  {
    id: 119,
    englishLabel: "Morocco",
    russianLabel: "Марокко",
    continent: "af",
  },
  {
    id: 120,
    englishLabel: "Martinique",
    russianLabel: "Мартиника",
    continent: "na",
  },
  {
    id: 121,
    englishLabel: "Marshall Is.",
    russianLabel: "Маршалловы о-ва",
    continent: "oc",
  },
  { id: 122, englishLabel: "Mexico", russianLabel: "Мексика", continent: "sa" },
  {
    id: 123,
    englishLabel: "Micronesia",
    russianLabel: "Микронезия",
    continent: "oc",
  },
  {
    id: 124,
    englishLabel: "Mozambique",
    russianLabel: "Мозамбик",
    continent: "af",
  },
  {
    id: 125,
    englishLabel: "Moldova",
    russianLabel: "Молдавия",
    continent: "eu",
  },
  { id: 126, englishLabel: "Monaco", russianLabel: "Монако", continent: "eu" },
  {
    id: 127,
    englishLabel: "Mongolia",
    russianLabel: "Монголия",
    continent: "as",
  },
  {
    id: 128,
    englishLabel: "Montserrat",
    russianLabel: "Монтсеррат",
    continent: "na",
  },
  { id: 129, englishLabel: "Myanmar", russianLabel: "Мьянма", continent: "as" },
  {
    id: 130,
    englishLabel: "Namibia",
    russianLabel: "Намибия",
    continent: "af",
  },
  { id: 131, englishLabel: "Nauru", russianLabel: "Науру", continent: "oc" },
  { id: 132, englishLabel: "Nepal", russianLabel: "Непал", continent: "as" },
  { id: 133, englishLabel: "Niger", russianLabel: "Нигер", continent: "af" },
  {
    id: 134,
    englishLabel: "Nigeria",
    russianLabel: "Нигерия",
    continent: "af",
  },
  {
    id: 135,
    englishLabel: "Netherlands",
    russianLabel: "Нидерланды",
    continent: "eu",
  },
  {
    id: 136,
    englishLabel: "Nicaragua",
    russianLabel: "Никарагуа",
    continent: "na",
  },
  { id: 137, englishLabel: "Niue", russianLabel: "Ниуэ", continent: "oc" },
  {
    id: 138,
    englishLabel: "New Zealand",
    russianLabel: "Новая Зеландия",
    continent: "oc",
  },
  {
    id: 139,
    englishLabel: "New Caledonia",
    russianLabel: "Новая Каледония",
    continent: "oc",
  },
  {
    id: 140,
    englishLabel: "Norway",
    russianLabel: "Норвегия",
    continent: "eu",
  },
  {
    id: 141,
    englishLabel: "United Arab Emirates",
    russianLabel: "Объединенные Арабские Эмираты",
    continent: "as",
  },
  { id: 142, englishLabel: "Oman", russianLabel: "Оман", continent: "as" },
  {
    id: 143,
    englishLabel: "Pakistan",
    russianLabel: "Пакистан",
    continent: "as",
  },
  { id: 144, englishLabel: "Palau", russianLabel: "Палау", continent: "oc" },
  {
    id: 145,
    englishLabel: "Palestine",
    russianLabel: "Палестина",
    continent: "as",
  },
  { id: 146, englishLabel: "Panama", russianLabel: "Панама", continent: "na" },
  {
    id: 147,
    englishLabel: "Papua New Guinea",
    russianLabel: "Папуа-Новая Гвинея",
    continent: "oc",
  },
  {
    id: 148,
    englishLabel: "Paraguay",
    russianLabel: "Парагвай",
    continent: "sa",
  },
  { id: 149, englishLabel: "Peru", russianLabel: "Перу", continent: "sa" },
  { id: 150, englishLabel: "Poland", russianLabel: "Польша", continent: "eu" },
  {
    id: 151,
    englishLabel: "Portugal",
    russianLabel: "Португалия",
    continent: "eu",
  },
  {
    id: 152,
    englishLabel: "Puerto Rico",
    russianLabel: "Пуэрто-Рико",
    continent: "na",
  },
  {
    id: 153,
    englishLabel: "Reunion",
    russianLabel: "Реюньон",
    continent: "af",
  },
  { id: 154, englishLabel: "Russia", russianLabel: "Россия", continent: "eu" },
  { id: 155, englishLabel: "Rwanda", russianLabel: "Руанда", continent: "af" },
  {
    id: 156,
    englishLabel: "Romania",
    russianLabel: "Румыния",
    continent: "eu",
  },
  {
    id: 157,
    englishLabel: "Salvador",
    russianLabel: "Сальвадор",
    continent: "na",
  },
  { id: 158, englishLabel: "Samoa", russianLabel: "Самоа", continent: "oc" },
  {
    id: 159,
    englishLabel: "San Marino",
    russianLabel: "Сан-Марино",
    continent: "eu",
  },
  {
    id: 160,
    englishLabel: "Sao Tome & Principe",
    russianLabel: "Сан-Томе и Принсипи",
    continent: "af",
  },
  {
    id: 161,
    englishLabel: "Saudi Arabia",
    russianLabel: "Саудовская Аравия",
    continent: "as",
  },
  {
    id: 162,
    englishLabel: "Is. of St martin",
    russianLabel: "о. Святого Мартина",
    continent: "na",
  },
  {
    id: 163,
    englishLabel: "Is. of St Helena",
    russianLabel: "о. Святой Елены",
    continent: "af",
  },
  {
    id: 164,
    englishLabel: "North Macedonia",
    russianLabel: "Северная Македония",
    continent: "eu",
  },
  {
    id: 165,
    englishLabel: "Northern Mariana Is.",
    russianLabel: "Северные Марианские о-ва",
    continent: "oc",
  },
  {
    id: 166,
    englishLabel: "Seychelles Is.",
    russianLabel: "Сейшельские о-ва",
    continent: "as",
  },
  {
    id: 167,
    englishLabel: "Senegal",
    russianLabel: "Сенегал",
    continent: "af",
  },
  {
    id: 168,
    englishLabel: "Saint Vincent & the Grenadines",
    russianLabel: "Сент-Винсент и Гренадины",
    continent: "na",
  },
  {
    id: 169,
    englishLabel: "Saint Kitts & Nevis",
    russianLabel: "Сент-Китс и Невис",
    continent: "na",
  },
  {
    id: 170,
    englishLabel: "Saint Lucia",
    russianLabel: "Сент-Люсия",
    continent: "na",
  },
  { id: 171, englishLabel: "Serbia", russianLabel: "Сербия", continent: "eu" },
  {
    id: 172,
    englishLabel: "Singapore",
    russianLabel: "Сингапур",
    continent: "as",
  },
  {
    id: 173,
    englishLabel: "Slovakia",
    russianLabel: "Словакия",
    continent: "eu",
  },
  {
    id: 174,
    englishLabel: "Slovenia",
    russianLabel: "Словения",
    continent: "eu",
  },
  {
    id: 175,
    englishLabel: "Solomon Is.",
    russianLabel: "Соломоновы о-ва",
    continent: "oc",
  },
  { id: 176, englishLabel: "Somalia", russianLabel: "Сомали", continent: "af" },
  {
    id: 177,
    englishLabel: "Suriname",
    russianLabel: "Суринам",
    continent: "sa",
  },
  {
    id: 178,
    englishLabel: "Sierra Leone",
    russianLabel: "Сьерра-Леоне",
    continent: "af",
  },
  { id: 179, englishLabel: "USA", russianLabel: "США", continent: "na" },
  {
    id: 180,
    englishLabel: "Tajikistan",
    russianLabel: "Таджикистан",
    continent: "as",
  },
  {
    id: 181,
    englishLabel: "Thailand",
    russianLabel: "Таиланд",
    continent: "as",
  },
  { id: 182, englishLabel: "Taiwan", russianLabel: "Тайвань", continent: "as" },
  {
    id: 183,
    englishLabel: "Tanzania",
    russianLabel: "Танзания",
    continent: "afoc",
  },
  {
    id: 184,
    englishLabel: "Timor Leste",
    russianLabel: "Тимор-Лесте",
    continent: "as",
  },
  { id: 185, englishLabel: "Togo", russianLabel: "Того", continent: "af" },
  {
    id: 186,
    englishLabel: "Tokelau",
    russianLabel: "Токелау",
    continent: "oc",
  },
  { id: 187, englishLabel: "Tonga", russianLabel: "Тонга", continent: "oc" },
  {
    id: 188,
    englishLabel: "Trinidad & Tobago",
    russianLabel: "Тринидад и Тобаго",
    continent: "sa",
  },
  { id: 189, englishLabel: "Tuvalu", russianLabel: "Тувалу", continent: "oc" },
  { id: 190, englishLabel: "Tunisia", russianLabel: "Тунис", continent: "af" },
  {
    id: 191,
    englishLabel: "Turkmenistan",
    russianLabel: "Туркменистан",
    continent: "as",
  },
  { id: 192, englishLabel: "Turkey", russianLabel: "Турция", continent: "eu" },
  { id: 193, englishLabel: "Uganda", russianLabel: "Уганда", continent: "af" },
  {
    id: 194,
    englishLabel: "Uzbekistan",
    russianLabel: "Узбекистан",
    continent: "as",
  },
  {
    id: 195,
    englishLabel: "Ukraine",
    russianLabel: "Украина",
    continent: "eu",
  },
  {
    id: 196,
    englishLabel: "Uruguay",
    russianLabel: "Уругвай",
    continent: "sa",
  },
  {
    id: 197,
    englishLabel: "Faroe Is.",
    russianLabel: "Фарерские о-ва",
    continent: "eu",
  },
  {
    id: 198,
    englishLabel: "Is. Fiji",
    russianLabel: "о. Фиджи",
    continent: "oc",
  },
  {
    id: 199,
    englishLabel: "Philippines",
    russianLabel: "Филипины",
    continent: "as",
  },
  {
    id: 200,
    englishLabel: "Finland",
    russianLabel: "Финляндия",
    continent: "eu",
  },
  {
    id: 201,
    englishLabel: "Falkland Is.",
    russianLabel: "Фолклендские о-ва",
    continent: "sa",
  },
  { id: 202, englishLabel: "France", russianLabel: "Франция", continent: "eu" },
  {
    id: 203,
    englishLabel: "French Guiana",
    russianLabel: "Французская Гвиана",
    continent: "sa",
  },
  {
    id: 204,
    englishLabel: "French Polynesia",
    russianLabel: "Французская Полинезия",
    continent: "oc",
  },
  {
    id: 205,
    englishLabel: "Croatia",
    russianLabel: "Хорватия",
    continent: "eu",
  },
  {
    id: 206,
    englishLabel: "Central African Republic",
    russianLabel: "ЦАР",
    continent: "af",
  },
  { id: 207, englishLabel: "Chad", russianLabel: "Чад", continent: "af" },
  {
    id: 208,
    englishLabel: "Montenegro",
    russianLabel: "Черногория",
    continent: "eu",
  },
  { id: 209, englishLabel: "Czech", russianLabel: "Чехия", continent: "eu" },
  { id: 210, englishLabel: "Chile", russianLabel: "Чили", continent: "sa" },
  {
    id: 211,
    englishLabel: "Switzerland",
    russianLabel: "Швейцария",
    continent: "eu",
  },
  { id: 212, englishLabel: "Sweden", russianLabel: "Швеция", continent: "eu" },
  {
    id: 213,
    englishLabel: "Svalbard & Jan Mayen",
    russianLabel: "Шпицберген и Ян-Майен",
    continent: "eu",
  },
  {
    id: 214,
    englishLabel: "Sri Lanka",
    russianLabel: "Шри-Ланка",
    continent: "as",
  },
  {
    id: 215,
    englishLabel: "Ecuador",
    russianLabel: "Эквадор",
    continent: "sa",
  },
  {
    id: 216,
    englishLabel: "Equatorial Guinea",
    russianLabel: "Экваториальная Гвинея",
    continent: "af",
  },
  {
    id: 217,
    englishLabel: "Eritrea",
    russianLabel: "Эритрея",
    continent: "af",
  },
  {
    id: 218,
    englishLabel: "Eswatini",
    russianLabel: "Эсватини",
    continent: "af",
  },
  {
    id: 219,
    englishLabel: "Estonia",
    russianLabel: "Эстония",
    continent: "eu",
  },
  {
    id: 220,
    englishLabel: "Ethiopia",
    russianLabel: "Эфиопия",
    continent: "af",
  },
  {
    id: 221,
    englishLabel: "South Africa",
    russianLabel: "Южная Африка",
    continent: "af",
  },
  {
    id: 222,
    englishLabel: "South Georgia & the South Sandwich Is.",
    russianLabel: "Южная Георгия и Южные Сандвичевы о-ва",
    continent: "sa",
  },
  {
    id: 223,
    englishLabel: "South Korea",
    russianLabel: "Южная Корея",
    continent: "as",
  },
  {
    id: 224,
    englishLabel: "South Sudan",
    russianLabel: "Южный Судан",
    continent: "af",
  },
  { id: 225, englishLabel: "Jamaica", russianLabel: "Ямайка", continent: "na" },
  { id: 226, englishLabel: "Japan", russianLabel: "Япония", continent: "as" },
];
